jobs:
  - name: dataworks-internet-ingress-pr
    plan:
      - get: dataworks-internet-ingress-pr
        trigger: true
        version: every
      - put: dataworks-internet-ingress-pr
        params:
          path: dataworks-internet-ingress-pr
          status: pending
        input_mapping:
          dataworks-internet-ingress: dataworks-internet-ingress-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-internet-ingress: dataworks-internet-ingress-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-internet-ingress: dataworks-internet-ingress-pr
        params:
          TF_WORKSPACE: 'qa'
          DETAILED_EXITCODE: ''
        on_failure:
          put: dataworks-internet-ingress-pr
          params:
            path: dataworks-internet-ingress-pr
            status: failure
        on_success:
          put: dataworks-internet-ingress-pr
          params:
            path: dataworks-internet-ingress-pr
            status: success
